definition_version: 2
entities:
  pipeline_monitor:
    type: streamlit
    identifier:
      name: PIPELINE_MONITOR
      database: CARDWORKS_DEMO
      schema: MARTS
    query_warehouse: MARKETING_DATA_FOUNDATION_WAREHOUSE
    runtime_name: SYSTEM$ST_CONTAINER_RUNTIME_PY3_11
    compute_pool: SYSTEM_COMPUTE_POOL_CPU
    main_file: streamlit_app.py
    artifacts:
      - streamlit_app.py
